version: '3.8'

services:
  appdeliverypublicapi:
    image: appdeliverypublicapi
    restart: always
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    depends_on:
      - "postgres"
      - "postgres_2"
    ports:
      - "5000:80"
    networks:
      - aspnetcoreapp-network

  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: "AppDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qazwsx321"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432"
    networks:
      - aspnetcoreapp-network

  postgres_2:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: "AppIdentityDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qazwsx321"
      PGDATA: /data/postgres
    volumes:
      - postgres_2:/data/postgres
    ports:
      - "5432"
    networks:
      - aspnetcoreapp-network

volumes:
  postgres:
    driver: local
  postgres_2:
    driver: local

networks:
  aspnetcoreapp-network:
    driver: bridge
  
    